# Generated by Django 3.2.5 on 2021-07-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldsvalue',
            name='analys',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainApp.analys', verbose_name='Анализ'),
        ),
    ]
