# Generated by Django 3.2.5 on 2021-07-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_extrafieldsvalue_analys'),
    ]

    operations = [
        migrations.AddField(
            model_name='analys',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Слаг код'),
        ),
    ]
