# Generated by Django 3.2.5 on 2021-07-28 08:37

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_analys_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracontacts',
            options={'verbose_name': 'Дополнительные контакты', 'verbose_name_plural': 'Дополнительные контакты'},
        ),
        migrations.AlterModelOptions(
            name='felials',
            options={'verbose_name': 'Филиаллы', 'verbose_name_plural': 'Филиаллы'},
        ),
        migrations.AddField(
            model_name='analys',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes', verbose_name='QR код'),
        ),
        migrations.AddField(
            model_name='felials',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='felials',
            name='photo',
            field=models.ImageField(default='net_photo.png', upload_to='felials/'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='photo',
            field=models.ImageField(default='net_photo.png', upload_to='felials/'),
        ),
        migrations.AlterField(
            model_name='analys',
            name='analys_finish_datetime',
            field=models.DateTimeField(blank=True, default=mainApp.models.default_datetime, verbose_name='Дата и время подготовки анализов'),
        ),
        migrations.AlterField(
            model_name='extracontacts',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_contacts', to='mainApp.myinfo'),
        ),
        migrations.AlterField(
            model_name='felials',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felials', to='mainApp.myinfo'),
        ),
    ]
