# Generated by Django 3.2.5 on 2021-07-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210728_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analys',
            name='analys_finish_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подготовки анализов'),
        ),
        migrations.AlterField(
            model_name='extrafields',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='mainApp.analystype', verbose_name='Вид анализов'),
        ),
        migrations.AlterField(
            model_name='extrafieldsvalue',
            name='analys',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mainApp.analys', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='extrafieldsvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mainApp.extrafields', verbose_name='Поле'),
        ),
    ]
