# Generated by Django 3.2.5 on 2021-08-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_analystype_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория анализов',
                'verbose_name_plural': 'Категория анализов',
            },
        ),
        migrations.AddField(
            model_name='analystype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='analystype',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Отображение на главной'),
        ),
        migrations.AddField(
            model_name='analystype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category', verbose_name='Категория'),
        ),
    ]
