# Generated by Django 3.2.5 on 2021-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210802_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analystype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена'),
        ),
    ]
