# Generated by Django 3.2.5 on 2021-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_analystype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='opened_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Открыто с '),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='opened_until',
            field=models.TimeField(blank=True, null=True, verbose_name='Открыто до '),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='week_days_off',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дни недели, в которые заведение закрыто (Воск.)'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='week_days_opened',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дни недели, в которые заведение открыто (Пон. - Суб.)'),
        ),
    ]
