# Generated by Django 3.2.5 on 2021-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210803_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на facebook'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на instagram'),
        ),
    ]
