# Generated by Django 3.2.5 on 2021-08-03 17:20

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0010_auto_20210803_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carusel', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('button', models.BooleanField(verbose_name='Отображать кнопку')),
                ('button_title', models.CharField(blank=True, max_length=255, verbose_name='Надпись на кнопке')),
                ('href', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать на главной')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусель',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Письмо')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 22, 20, 10, 389431))),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_logo', models.ImageField(default='net-photo.png', upload_to='services/mini_logo', verbose_name='Мини изображение')),
                ('logo', models.ImageField(default='net-photo.png', upload_to='services/logo', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('show', models.BooleanField(default=False, verbose_name='Отображение на главной')),
                ('show_price', models.BooleanField(default=False, verbose_name='Отображать на прайс листе')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='analystype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='analystype',
            name='show',
        ),
        migrations.AddField(
            model_name='felials',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='show_price_list',
            field=models.BooleanField(default=True, verbose_name='Отображать price list'),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('logo', models.ImageField(upload_to='blogs', verbose_name='Обложка статьи')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Блог')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 22, 20, 10, 390430), verbose_name='Дата и время публикации')),
                ('watch', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug код')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Блоги',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 22, 20, 10, 389431))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
