# Generated by Django 3.2.5 on 2021-08-04 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20210804_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='analys',
            name='comments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='analys',
            name='method',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Метод исследования'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 3, 37, 31, 711847)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 3, 37, 31, 713845), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 3, 37, 31, 711847)),
        ),
    ]
