# Generated by Django 3.2 on 2021-08-06 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20210805_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 1, 33, 48, 334723)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 1, 33, 48, 335721), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 1, 33, 48, 334723)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 1, 33, 48, 336725), verbose_name='Дата и время')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать в списке записей')),
                ('felial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appintments', to='mainApp.felials', verbose_name='Адрес')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appontments', to='mainApp.services', verbose_name='Процедура/услуга')),
            ],
            options={
                'verbose_name': 'Записи на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
    ]
