# Generated by Django 3.2 on 2021-08-08 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210807_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='mini_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мини описание (20 слов макс.)'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 5, 31, 49, 170833)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 5, 31, 49, 172834), verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 5, 31, 49, 172834), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 5, 31, 49, 170833)),
        ),
    ]
