# Generated by Django 3.2 on 2021-08-08 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20210809_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='telegram',
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 2, 1, 41, 550846)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 2, 1, 41, 551846), verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 2, 1, 41, 551846), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на facebook'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 2, 1, 41, 549845)),
        ),
    ]
