# Generated by Django 3.2 on 2021-08-08 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20210809_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.CharField(max_length=255, null=True, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 3, 35, 50, 655818)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 3, 35, 50, 656820), verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 3, 35, 50, 656820), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 3, 35, 50, 654817)),
        ),
    ]
