# Generated by Django 3.2.5 on 2021-08-09 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_auto_20210809_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Социальный статус/должность (поле не обязателно для ввода)')),
                ('photo', models.ImageField(default='no_user.png', upload_to='reviews', verbose_name='Фотография')),
                ('review', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='myinfo',
            name='cheff_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя владельца'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='cheff_photo',
            field=models.ImageField(default='no_user.png', upload_to='cheff', verbose_name='Фото владельца'),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='favicon',
            field=models.ImageField(default='net_photo.png', upload_to='favicon', verbose_name='Фавикон'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 42, 20, 901011)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 42, 20, 903009), verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 42, 20, 902010), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 14, 42, 20, 899012)),
        ),
    ]
